### ISSUE TITLE
Error to write yaml

### ISSUE THREAD

**Issue by brauliobo** [tenderlove/syck#7]
```
{:management_information=>nil,
 :acronym=>nil,
 :city=>"Chapada dos GuimarÃ£es",
 :contact_person=>nil,
 :organization_website=>"",
 :foundation_year=>nil,
 :layout_template=>"leftbar",
 :legal_form=>nil,
 :closed=>true,
 :state=>"Mato Grosso",
 :referer=>"F\xC3\xB3rum",
 :economic_activity=>nil,
 :contact_email=>
  #<ActiveSupport::Multibyte::Chars:0xc16aeac
   @wrapped_string="aitanabrasil@gmail.com">}
rake aborted!
NoMethodError: undefined method `write' for #<Syck::Emitter:0xc17f438>
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/syck-1.0.4/lib/syck/rubytypes.rb:43:in `node_export'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/syck-1.0.4/lib/syck/rubytypes.rb:43:in `add'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/syck-1.0.4/lib/syck/rubytypes.rb:43:in `block (3 levels) in to_yaml'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/syck-1.0.4/lib/syck/rubytypes.rb:42:in `each'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/syck-1.0.4/lib/syck/rubytypes.rb:42:in `block (2 levels) in to_yaml'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/syck-1.0.4/lib/syck/rubytypes.rb:41:in `map'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/syck-1.0.4/lib/syck/rubytypes.rb:41:in `block in to_yaml'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/syck-1.0.4/lib/syck.rb:411:in `call'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/syck-1.0.4/lib/syck.rb:411:in `emit'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/syck-1.0.4/lib/syck.rb:411:in `quick_emit'
/home/braulio/.rvm/gems/ruby-2.1.3@noosfero/gems/syck-1.0.4/lib/syck/rubytypes.rb:40:in `to_yaml'
```

**Comment by hsbt** [comment]
It's no information for investigation.
